<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Telegram.Bot" Version="22.9.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ProjectBullet.Core\ProjectBullet.Core.csproj" />
    </ItemGroup>

</Project>
