name: Build + Release | Staging

on:
  push:
    branches:
    - 'staging'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # Run if commit message contains [build] or if manually triggered
    if: contains(github.event.head_commit.message || '', '[build]') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Unit and integration tests
      run: dotnet test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Get the commit number
    - name: Get commit number
      run: echo "COMMIT_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV

    # Read the version
    - name: Read version
      run: echo "VERSION=$(head -n 1 ProjectBullet.Native/version.txt)" >> $GITHUB_ENV

    # Overwrite the contents of version.txt with $VERSION.$COMMIT_NUMBER
    - name: Append commit number to version.txt
      run: echo "${{ env.VERSION }}.${{ env.COMMIT_NUMBER }}" > ProjectBullet.Native/version.txt

    # Get the commit description
    - name: Get commit description
      run: |
        echo 'COMMIT_DESCRIPTION<<EOF' >> $GITHUB_ENV
        git log -1 --pretty=%b >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    # Read the version again
    - name: Read version again
      run: echo "VERSION=$(head -n 1 ProjectBullet.Native/version.txt)" >> $GITHUB_ENV

    # Build native client
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build Native Client (win-x64)
      run: dotnet publish ProjectBullet.Native -c Release -r win-x64 --self-contained false -o ./build/native-win-x64

    - name: Build Native Client (win-x86)
      run: dotnet publish ProjectBullet.Native -c Release -r win-x86 --self-contained false -o ./build/native-win-x86

    - name: Build Native Client (win-arm64)
      run: dotnet publish ProjectBullet.Native -c Release -r win-arm64 --self-contained false -o ./build/native-win-arm64

    - name: Build Native Updater (win-x64)
      run: dotnet publish ProjectBullet.Native.Updater -c Release -r win-x64 -o ./build/updater-win-x64

    - name: Build Native Updater (win-x86)
      run: dotnet publish ProjectBullet.Native.Updater -c Release -r win-x86 -o ./build/updater-win-x86

    - name: Build Native Updater (win-arm64)
      run: dotnet publish ProjectBullet.Native.Updater -c Release -r win-arm64 -o ./build/updater-win-arm64

    # Package release artifacts
    - name: Package release artifacts
      run: |
        mkdir -p .release
        cd ./build/native-win-x64
        zip -r ../../.release/ProjectBullet.Native-win-x64.zip ./*
        cd ../native-win-x86
        zip -r ../../.release/ProjectBullet.Native-win-x86.zip ./*
        cd ../native-win-arm64
        zip -r ../../.release/ProjectBullet.Native-win-arm64.zip ./*
        cd ../..
        cp ./build/updater-win-x64/ProjectBullet.Native.Updater.exe .release/pb-native-updater-win-x64.exe
        cp ./build/updater-win-x86/ProjectBullet.Native.Updater.exe .release/pb-native-updater-win-x86.exe
        cp ./build/updater-win-arm64/ProjectBullet.Native.Updater.exe .release/pb-native-updater-win-arm64.exe

    # Upload the files to the release
    - name: Upload ProjectBullet staging release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '.release/*'
        file_glob: true
        release_name: ${{ env.VERSION }}
        tag: ${{ env.VERSION }}
        overwrite: false
        prerelease: true
        make_latest: true
        body: |
          ## ProjectBullet ${{ env.VERSION }} (Staging)

          This is a **STAGING** build. It might be unstable. Use at your own discretion.

          ### Changelog
          ${{ env.COMMIT_DESCRIPTION }}

    - name: Notify new build on discord
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: |
          [
            {
              "title": "New ProjectBullet Staging Build",
              "description": "Staging release **${{ env.VERSION }}** available",
              "color": 5763719
            }
          ]
      uses: Ilshidur/action-discord@master

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      if: ${{ failure() }}
      with:
        wait-timeout-minutes: 5
